// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TradeGame
{
    public partial class TradeGameModel
    {
        /// <summary>
        /// model input class for TradeGameModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Action")]
            public string Action { get; set; }

            [ColumnName(@"Resource")]
            public string Resource { get; set; }

            [ColumnName(@"Amount")]
            public float Amount { get; set; }

            [ColumnName(@"Transferring")]
            public string Transferring { get; set; }

            [ColumnName(@"Receiving")]
            public string Receiving { get; set; }

            [ColumnName(@"EU")]
            public float EU { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TradeGameModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Action")]
            public float[] Action { get; set; }

            [ColumnName(@"Resource")]
            public float[] Resource { get; set; }

            [ColumnName(@"Amount")]
            public float Amount { get; set; }

            [ColumnName(@"Transferring")]
            public float[] Transferring { get; set; }

            [ColumnName(@"Receiving")]
            public float[] Receiving { get; set; }

            [ColumnName(@"EU")]
            public float EU { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TradeGameModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
