﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace TradeGame
{
    public partial class TradeGameModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"Action", @"Action"),new InputOutputColumnPair(@"Transferring", @"Transferring"),new InputOutputColumnPair(@"Receiving", @"Receiving")})      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(@"Amount", @"Amount"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"Resource",outputColumnName:@"Resource"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Action",@"Transferring",@"Receiving",@"Amount",@"Resource"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.FastTreeTweedie(new FastTreeTweedieTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=102,NumberOfTrees=84,MaximumBinCountPerFeature=940,FeatureFraction=0.916713413503691,LearningRate=0.999999776672986,LabelColumnName=@"EU",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
